name: Deploy to github pages

on:
  push: 

jobs:
  build:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Build-prod
        run: yarn build-prod

      - name: Test
        run: yarn test

      - name: Commit (publish to gh-pages)
        run: |
          git config user.name "actions"
          git fetch
          git checkout --orphan gh-pages
          git --work-tree dist add --all
          git --work-tree dist commit -m gh-pages
          git push origin HEAD:gh-pages --force
