name: Deploy to github pages

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      
      - name: ls
        run: ls

      - name: Git branch
        run: |
          git config user.name "a.baschuk" && git config user.email "a.baschuk@dodopizza.com"
          git checkout --orphan gh-pages

      - name: Install modules
        run: yarn

      - name: Build bundle
        run: yarn build

      - name: Git commit
        run: |
          git --work-tree dist add --all
          git --work-tree dist commit -m gh-pages
          git push origin HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
